{
  "name": "throw-error",
  "version": "1.0.0",
  "description": "create a function that when called will throw an error with the provided error message.",
  "main": "lib/index.js",
  "types": "lib/index.d.ts",
  "scripts": {
    "test": "jest --config jestconfig.json",
    "build": "tsc",
    "format": "prettier --write \"src/**/*.ts\"",
    "lint": "tslint -p tsconfig.json",
    "prepare" : "npm run build",
    "prepublishOnly" : "npm test && npm run lint",
    "preversion" : "npm run lint",
    "version" : "npm run format && git add -A src",
    "postversion" : "git push && git push --tags"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/DucktorScience/throw-error.git"
  },
  "author": "",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/DucktorScience/throw-error/issues"
  },
  "homepage": "https://github.com/DucktorScience/throw-error#readme",
  "devDependencies": {
    "@types/jest": "^26.0.20",
    "jest": "^26.6.3",
    "prettier": "^2.2.1",
    "ts-jest": "^26.5.3",
    "tslint": "^6.1.3",
    "tslint-config-prettier": "^1.18.0",
    "typescript": "^4.2.3"
  },
  "files": [
    "lib/**/*"
  ]
}
